version: '2.2'
services:
  webpython:
    build: ./python
    ports:
     - "5000"
    volumes:
     - ./python:/code
    entrypoint: ["python", "app.py"]
    logging:
     driver: json-file
     options:
      max-size: "200k"
      max-file: "10"

  webnode:
    build: ./node
    ports:
     - "3000"
    volumes:
     - ./node/app.js:/usr/src/app/app.js
    #entrypoint: ["npm", "run", "app"]
    logging:
     driver: json-file
     options:
      max-size: "200k"
      max-file: "10"
    environment:
      APP_PORT: 3000

  nginx:
    build: ./nginx/
    image: "nginx:alpine"
    ports:
     - "443:443"
    volumes:
     - ./nginx/mysite.template:/etc/nginx/conf.d/mysite.template
     - nginxlog:/var/log/nginx
    environment:
      NODE_PORT: 3000
      APP_PORT: 5000
    command: /bin/bash -c "printenv; envsubst '$NODE_PORT,$APP_PORT'  < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && cat /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    logging:
     driver: json-file
     options:
      max-size: "200k"
      max-file: "10"

  redis:
    image: "redis:alpine"
    ports:
     - "6379:6379"    
    volumes:
     - dbdata:/data
    logging:
     driver: json-file
     options:
      max-size: "200k"
      max-file: "10"
    mem_limit: 300m
    mem_reservation: 100m
    cpus: 0.5

  ubuntu:
    image: "ubuntu:latest"

volumes:
  nginxlog:
  dbdata: